[package]
name = "kn-tx"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = { version = "1.48.0", features = ["full", "rt-multi-thread"] }
